apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-statefulset
  labels:
    app: influxdb-sfs
spec:
  serviceName: influxdb
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-sfs
  template:
    metadata:
      labels:
        app: influxdb-sfs
    spec:
      containers:
      - name: influxdb
        image: influxdb-img
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps -o comm | grep 'telegraf' && ps -o comm | grep 'influxdb'
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-volume
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb-sfs
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
