apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-depl
  template:
    metadata:
      labels:
        app: mysql-depl
    spec:
      containers:
        - name: mysql
          image: mysql-img
          ports:
          - containerPort: 3306
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-depl
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
