apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-depl
  template:
    metadata:
      labels:
        app: php-depl
    spec:
      containers:
        - name: phpmyadmin
          image: php-img
          ports:
          - containerPort: 5000
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps -o comm | grep 'telegraf' && ps -o comm | grep 'nginx' && ps -o comm | grep 'php-fpm7'
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip : shared
spec:
  selector:
    app: php-depl
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
