apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-depl
  template:
    metadata:
      labels:
        app: ftps-depl
    spec:
      containers:
      - name: ftps
        image: ftps-img
        ports:
          - containerPort: 21
          - containerPort: 30020
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip : shared
spec:
  selector:
    app: ftps-depl
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv
      port: 30020
      targetPort: 30020
  type: LoadBalancer
