apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-depl
  template:
    metadata:
      labels:
        app: wp-depl
    spec:
      containers:
        - name: phpmyadmin
          image: wp-img
          ports:
          - containerPort: 5050
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps -o comm | grep 'telegraf' && ps -o comm | grep 'nginx' && ps -o comm |  grep 'php-fpm7'
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip : shared
spec:
  selector:
    app: wp-depl
  ports:
    - name:
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
